# Generated by Django 3.2.4 on 2021-06-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdAt',
            field=models.IntegerField(),
        ),
    ]
